version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: relstorage[postgresql]
    versions:
    - 3.4.0
    - 3.4.1
    - 3.4.2
  - dependency-name: keyring
    versions:
    - 22.0.0
